/* DO NOT EDIT THIS FILE - it is machine generated */
#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
//#include "pch.h"
/* Header for class com_brandonhessler_Attenuator_AttenuatorJni */

#ifndef _Included_com_brandonhessler_Attenuator_AttenuatorJni
#define _Included_com_brandonhessler_Attenuator_AttenuatorJni
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_brandonhessler_Attenuator_AttenuatorJni
	* Method:    connect
	* Signature: (II)Z
	*/
	JNIEXPORT jboolean JNICALL Java_com_brandonhessler_Attenuator_AttenuatorJni_connect
		(JNIEnv *, jobject, jint, jint);

	/*
	* Class:     com_brandonhessler_Attenuator_AttenuatorJni
	* Method:    start
	* Signature: (I)Z
	*/
	JNIEXPORT jboolean JNICALL Java_com_brandonhessler_Attenuator_AttenuatorJni_start
		(JNIEnv *, jobject, jint);

	/*
	* Class:     com_brandonhessler_Attenuator_AttenuatorJni
	* Method:    stop
	* Signature: ()Z
	*/
	JNIEXPORT jboolean JNICALL Java_com_brandonhessler_Attenuator_AttenuatorJni_stop
		(JNIEnv *, jobject);

	/*
	* Class:     com_brandonhessler_Attenuator_AttenuatorJni
	* Method:    pause
	* Signature: ()Z
	*/
	JNIEXPORT jboolean JNICALL Java_com_brandonhessler_Attenuator_AttenuatorJni_pause
		(JNIEnv *, jobject);

	/*
	* Class:     com_brandonhessler_Attenuator_AttenuatorJni
	* Method:    box1OnOff
	* Signature: (Z)Z
	*/
	JNIEXPORT jboolean JNICALL Java_com_brandonhessler_Attenuator_AttenuatorJni_box1OnOff
		(JNIEnv *, jobject, jboolean);

	/*
	* Class:     com_brandonhessler_Attenuator_AttenuatorJni
	* Method:    box1StartVal
	* Signature: (I)Z
	*/
	JNIEXPORT jboolean JNICALL Java_com_brandonhessler_Attenuator_AttenuatorJni_box1StartVal
		(JNIEnv *, jobject, jint);

	/*
	* Class:     com_brandonhessler_Attenuator_AttenuatorJni
	* Method:    box2OnOff
	* Signature: (Z)Z
	*/
	JNIEXPORT jboolean JNICALL Java_com_brandonhessler_Attenuator_AttenuatorJni_box2OnOff
		(JNIEnv *, jobject, jboolean);

	/*
	* Class:     com_brandonhessler_Attenuator_AttenuatorJni
	* Method:    box2StartVal
	* Signature: (I)Z
	*/
	JNIEXPORT jboolean JNICALL Java_com_brandonhessler_Attenuator_AttenuatorJni_box2StartVal
		(JNIEnv *, jobject, jint);

	/*
	* Class:     com_brandonhessler_Attenuator_AttenuatorJni
	* Method:    setScanRate
	* Signature: (III)Z
	*/
	JNIEXPORT jboolean JNICALL Java_com_brandonhessler_Attenuator_AttenuatorJni_setScanRate
		(JNIEnv *, jobject, jint, jint, jint);

	/*
	* Class:     com_brandonhessler_Attenuator_AttenuatorJni
	* Method:    getAttenuationValues
	* Signature: ()[Ljava/lang/String;
	*/
	JNIEXPORT jobjectArray JNICALL Java_com_brandonhessler_Attenuator_AttenuatorJni_getAttenuationValues
		(JNIEnv *, jobject);

	/*
	* Class:     com_brandonhessler_Attenuator_AttenuatorJni
	* Method:    getStatus
	* Signature: ()[Z
	*/
	JNIEXPORT jobjectArray JNICALL Java_com_brandonhessler_Attenuator_AttenuatorJni_getStatus
		(JNIEnv *, jobject);

	/*
	* Class:     com_brandonhessler_Attenuator_AttenuatorJni
	* Method:    getData
	* Signature: ()[Ljava/lang/String;
	*/
	JNIEXPORT jobjectArray JNICALL Java_com_brandonhessler_Attenuator_AttenuatorJni_getData
		(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
